// import slugify from '../utils/slugify'
import {
  orderRankField,
  orderRankOrdering,
} from '@sanity/orderable-document-list';

export default {
  title: "Projects",
  name: 'projects',
  type: "document",
  orderings: [orderRankOrdering],
  fields: [
    orderRankField({ type: 'category', hidden: true }),
    {
      title: "Title",
      description: "The name of this project, eg: 'Malibu House'",
      name: "title",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: "Location",
      description: "The location of this project",
      name: "location",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: "Year",
      description: "The year of this project",
      name: "year",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: "Status",
      description: "The status of this project, eg: 'In Progress', 'Complete' etc...",
      name: "status",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: "Project Code",
      description: "The code for this project, eg: 'S.1071'",
      name: "projectCode",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: 'Images',
      name: 'images',
      description: 'The array of images for this project',
      type: 'array',
      of: [
        {
          name: 'image',
          type: 'defaultImage',
          title: 'Image',
        },
      ],
      options: {
        layout: 'grid',
      }
    },
    {
      title: 'Child Projects',
      name: 'childProjects',
      description: "If this is added, this project will open with children and no parent, overriding the images above.",
      type: 'array',
      of: [{type: 'childProject', title: 'Child Project'}],
    },
    // {
    //   name: 'slug',
    //   type: 'slug',
    //   title: 'Slug',
    //   description: 'This is required for page routing and can be auto-generated by pressing "generate"',
    //   options: {
    //     source: (doc) => {
    //       let titleSlug = ''
    //       let campaignSlug = ''
    //       if (doc.title) {
    //         titleSlug = `${doc.title}`
    //       } else {
    //         titleSlug = ''
    //       }

    //       if (doc.campaignTitle) {
    //         campaignSlug = `-${doc.campaignTitle}`
    //       } else {
    //         campaignSlug = ''
    //       }

    //       return `${titleSlug}${campaignSlug}`;
    //     },
    //     maxLength: 96,
    //     slugify: (input) => slugify(`${input}`)
    //   },
    //   validation: Rule => Rule.required()
    // }
  ],
  preview: {
    select: {
      title: 'title',
      location: 'location',
      images: 'images',
      projectCode: 'projectCode',
    },
    prepare(selection) {
      const {title, location, images, projectCode} = selection
      return {
        title: title,
        subtitle: `${projectCode} — ${location}`,
        media: images[0]
      }
    }
  }
}